[package]
name = "dotemplate"
version = "0.1.0"
edition = "2021"
description = "todo"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
enum_str = "0.1.2"
semver = "1.0.20"
